export const PAYPAL_STATUS = {
  CREATED: 'CREATED',
  SAVED: 'SAVED',
  APPROVED: 'APPROVED',
  VOIDED: 'VOIDED',
  COMPLETED: 'COMPLETED',
  PAYER_ACTION_REQUIRED: 'PAYER_ACTION_REQUIRED',
} as const;

export type TPaypalStatus = keyof typeof PAYPAL_STATUS;
